---
title: "git_00"
author: "Alejandra Sandoval"
date: "Spring 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->


And cannot pleasures, while they last,  
Be actual unless, when past,  
They leave us shuddering and aghast,  
With anguish smarting?  
And cannot friends be firm and fast,  


## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->


The city had withdrawn into itself  
And left at last the country to the country;  
When between whirls of snow not come to lie  
And whirls of foliage not yet laid, there drove  
A stranger to our yard, who looked the city,  


## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->


"The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make  
      The billows smooth and bright —  
And this was odd, because it was  
      The middle of the night.  

The moon was shining sulkily,  
      Because she thought the sun  
Had got no business to be there  
      After the day was done —  
"It's very rude of him," she said,  
      "To come and spoil the fun."  


## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->


The art of losing isn’t hard to master;  
so many things seem filled with the intent  
to be lost that their loss is no disaster.  

Lose something every day. Accept the fluster  
of lost door keys, the hour badly spent.  
The art of losing isn’t hard to master.  

Then practice losing farther, losing faster:  
places, and names, and where it was you meant  
to travel. None of these will bring disaster.  

I lost my mother’s watch. And look! my last, or  
next-to-last, of three loved houses went.  
The art of losing isn’t hard to master.  

I lost two cities, lovely ones. And, vaster,  
some realms I owned, two rivers, a continent.  
I miss them, but it wasn’t a disaster.  